name: .NET

on:
  push:
    branches: [ restructureBaseDir ]
  pull_request:
    branches: [ restructureBaseDir ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd mzLib
        dotnet restore
    - name: Build
      run: |
        cd mzLib
        dotnet build --no-restore
    - name: Test
      run: |
        cd mzLib
        dotnet test --no-build --verbosity normal Test/Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='coverage1.xml' /p:Exclude="./Test/*.cs%2c./TestFlashLFQ/*.cs"
        dotnet test --no-build --verbosity normal TestFlashLFQ/TestFlashLFQ.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='coverage2.xml' /p:Exclude="./Test/*.cs%2c./TestFlashLFQ/*.cs"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_KEY }}
        directory: ./coverage/reports/
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
